export default class ExternalSource {
    /**
     *
     * @param {{
    *      inner_container: HTMLDivElement;
    *      source_type: 'url' | 'onedrive' | 'google_drive' | 'clipboard' | 'box' | 'dalle';
    *      standalone?: boolean;
    *      callbackFn: Function;
    *      custup_close_btn?: HTMLDivElement;
    *      custup_show_message_fn?: Function;
    *      onclose?: Function;
    *      handle_custom_scroll?: {
    *       customScroll: Function;
    *       customScrollbar: Function;
    *      };
    *      allowed_mime_types: Array<keyof file_types>;
    *      config_override: {
    *          url: object;
    *          onedrive: object;
    *          google_drive: object;
    *          clipboard: object;
    *          box: object;
    *          dalle: object;
    *       };
    *       style_override: typeof external_sources_ui_styles;
    * }}
    */
    constructor({ inner_container, source_type, standalone, custup_close_btn, callbackFn, custup_show_message_fn, handle_custom_scroll, allowed_mime_types, onclose, config_override, style_override, setElementMediaQuery }: {
        inner_container: HTMLDivElement;
        source_type: 'url' | 'onedrive' | 'google_drive' | 'clipboard' | 'box' | 'dalle';
        standalone?: boolean;
        callbackFn: Function;
        custup_close_btn?: HTMLDivElement;
        custup_show_message_fn?: Function;
        onclose?: Function;
        handle_custom_scroll?: {
            customScroll: Function;
            customScrollbar: Function;
        };
        allowed_mime_types: Array<keyof {
            '123': string;
            '3dml': string;
            '3ds': string;
            '3g2': string;
            '3gp': string;
            '7z': string;
            aab: string;
            aac: string;
            aam: string;
            aas: string;
            abw: string;
            ac: string;
            acc: string;
            ace: string;
            acu: string;
            acutc: string;
            adp: string;
            aep: string;
            afm: string;
            afp: string;
            ahead: string;
            ai: string;
            aif: string;
            aifc: string;
            aiff: string;
            air: string;
            ait: string;
            ami: string;
            apk: string;
            appcache: string;
            application: string; /**
             * URL Source
             */
            apr: string;
            arc: string;
            asc: string;
            asf: string;
            asm: string;
            aso: string;
            asx: string;
            atc: string;
            atom: string;
            atomcat: string;
            atomsvc: string;
            atx: string;
            au: string;
            avi: string;
            aw: string;
            azf: string;
            azs: string;
            azw: string;
            bat: string;
            bcpio: string;
            bdf: string;
            bdm: string;
            bed: string;
            bh2: string;
            bin: string;
            blb: string;
            blorb: string;
            bmi: string;
            bmp: string;
            book: string;
            box: string;
            boz: string;
            bpk: string;
            btif: string;
            bz: string;
            bz2: string;
            c: string;
            c11amc: string;
            c11amz: string;
            c4d: string;
            c4f: string;
            c4g: string;
            c4p: string;
            c4u: string;
            cab: string;
            caf: string;
            cap: string;
            car: string;
            cat: string;
            cb7: string;
            cba: string;
            cbr: string;
            cbt: string;
            cbz: string;
            cc: string;
            cct: string;
            ccxml: string;
            cdbcmsg: string;
            cdf: string;
            cdkey: string;
            cdmia: string;
            cdmic: string;
            cdmid: string;
            cdmio: string;
            cdmiq: string;
            cdx: string;
            cdxml: string;
            cdy: string;
            cer: string;
            cfs: string;
            cgm: string;
            chat: string;
            chm: string;
            chrt: string;
            cif: string;
            cii: string;
            cil: string;
            cla: string;
            class: string;
            clkk: string;
            clkp: string;
            clkt: string;
            clkw: string;
            clkx: string;
            clp: string;
            cmc: string;
            cmdf: string;
            cml: string;
            cmp: string;
            cmx: string;
            cod: string;
            com: string;
            conf: string;
            cpio: string;
            cpp: string;
            cpt: string;
            crd: string;
            crl: string;
            crt: string;
            cryptonote: string;
            csh: string;
            csml: string;
            csp: string;
            css: string;
            cst: string;
            csv: string;
            cu: string;
            curl: string;
            cww: string;
            cxt: string;
            cxx: string;
            dae: string;
            daf: string;
            dart: string;
            dataless: string;
            davmount: string;
            dbk: string;
            dcr: string;
            dcurl: string;
            dd2: string;
            ddd: string;
            deb: string;
            def: string;
            deploy: string;
            der: string;
            dfac: string;
            dgc: string;
            dic: string;
            dir: string;
            dis: string;
            dist: string;
            distz: string;
            djv: string;
            djvu: string;
            dll: string;
            dmg: string;
            dmp: string;
            dms: string;
            dna: string;
            doc: string;
            docm: string;
            docx: string;
            dot: string;
            dotm: string;
            dotx: string;
            dp: string;
            dpg: string;
            dra: string;
            dsc: string;
            dssc: string;
            dtb: string;
            dtd: string;
            dts: string;
            dtshd: string;
            dump: string;
            dvb: string;
            dvi: string;
            dwf: string;
            dwg: string;
            dxf: string;
            dxp: string;
            dxr: string;
            ecelp4800: string;
            ecelp7470: string;
            ecelp9600: string;
            ecma: string;
            edm: string;
            edx: string;
            efif: string;
            ei6: string;
            elc: string;
            emf: string;
            eml: string;
            emma: string;
            emz: string;
            eol: string;
            eot: string;
            eps: string;
            epub: string;
            es3: string;
            esa: string;
            esf: string;
            et3: string;
            etx: string;
            eva: string;
            evy: string;
            exe: string;
            exi: string;
            ext: string;
            ez: string;
            ez2: string;
            ez3: string;
            f: string;
            f4v: string;
            f77: string;
            f90: string;
            fbs: string;
            fcdt: string;
            fcs: string;
            fdf: string;
            fe_launch: string;
            fg5: string;
            fgd: string;
            fh: string;
            fh4: string;
            fh5: string;
            fh7: string;
            fhc: string;
            fig: string;
            flac: string;
            fli: string;
            flo: string;
            flv: string;
            flw: string;
            flx: string;
            fly: string;
            fm: string;
            fnc: string;
            for: string;
            fpx: string;
            frame: string;
            fsc: string;
            fst: string;
            ftc: string;
            fti: string;
            fvt: string;
            fxp: string;
            fxpl: string;
            fzs: string;
            g2w: string;
            g3: string;
            g3w: string;
            gac: string;
            gam: string;
            gbr: string;
            gca: string;
            gdl: string;
            geo: string;
            gex: string;
            ggb: string;
            ggt: string;
            ghf: string;
            gif: string;
            gim: string;
            gml: string;
            gmx: string;
            gnumeric: string;
            gph: string;
            gpx: string;
            gqf: string;
            gqs: string;
            gram: string;
            gramps: string;
            gre: string;
            grv: string;
            grxml: string;
            gsf: string;
            gtar: string;
            gtm: string;
            gtw: string;
            gv: string;
            gxf: string;
            gxt: string;
            h: string;
            h261: string;
            h263: string;
            h264: string;
            hal: string;
            hbci: string;
            hdf: string;
            hh: string;
            hlp: string;
            hpgl: string;
            hpid: string;
            hps: string;
            hqx: string;
            htke: string;
            htm: string;
            html: string;
            hvd: string;
            hvp: string;
            hvs: string;
            i2g: string;
            icc: string;
            ice: string;
            icm: string;
            ico: string;
            ics: string;
            ief: string;
            ifb: string;
            ifm: string;
            iges: string;
            igl: string;
            igm: string;
            igs: string;
            igx: string;
            iif: string;
            imp: string; /**
             * @private getRandChars
             * @param {string} identifyer
             * @returns {string}
             */
            ims: string;
            in: string;
            ink: string;
            inkml: string;
            install: string;
            iota: string;
            ipfix: string;
            ipk: string;
            irm: string;
            irp: string;
            iso: string;
            itp: string;
            ivp: string;
            ivu: string;
            jad: string;
            jam: string;
            jar: string;
            java: string;
            javascript: string;
            jisp: string;
            jlt: string;
            jnlp: string;
            joda: string;
            jpe: string;
            jpeg: string;
            jpg: string;
            jpgm: string;
            jpgv: string;
            jpm: string;
            js: string;
            json: string;
            jsonml: string;
            kar: string;
            karbon: string;
            kfo: string;
            kia: string;
            kml: string;
            kmz: string;
            kne: string;
            knp: string;
            kon: string;
            kpr: string;
            kpt: string;
            kpxx: string;
            ksp: string;
            ktr: string;
            ktx: string;
            ktz: string;
            kwd: string;
            kwt: string;
            lasxml: string;
            latex: string;
            lbd: string;
            lbe: string;
            les: string;
            lha: string;
            link66: string;
            list: string;
            list3820: string;
            listafp: string;
            lnk: string;
            log: string;
            lostxml: string;
            lrf: string;
            lrm: string;
            ltf: string;
            lvp: string;
            lwp: string;
            lzh: string;
            m13: string;
            m14: string;
            m1v: string;
            m21: string;
            m2a: string;
            m2v: string;
            m3a: string;
            m3u: string;
            m3u8: string;
            m4a: string;
            m4u: string;
            m4v: string;
            ma: string;
            mads: string;
            mag: string;
            maker: string;
            man: string;
            mar: string;
            mathml: string;
            mb: string;
            mbk: string;
            mbox: string;
            mc1: string;
            mcd: string;
            mcurl: string;
            mdb: string;
            mdi: string;
            me: string;
            mesh: string;
            meta4: string;
            metalink: string;
            mets: string;
            mfm: string;
            mft: string;
            mgp: string;
            mgz: string;
            mid: string;
            midi: string;
            mie: string;
            mif: string;
            mime: string;
            mj2: string;
            mjp2: string;
            mjs: string;
            mk3d: string;
            mka: string;
            mks: string;
            mkv: string;
            mlp: string;
            mmd: string;
            mmf: string;
            mmr: string;
            mng: string;
            mny: string;
            mobi: string;
            mods: string;
            mov: string;
            movie: string;
            mp2: string;
            mp21: string;
            mp2a: string;
            mp3: string;
            mp4: string;
            mp4a: string;
            mp4s: string;
            mp4v: string;
            mpc: string;
            mpe: string;
            mpeg: string;
            mpg: string;
            mpg4: string;
            mpga: string;
            mpkg: string;
            mpm: string;
            mpn: string;
            mpp: string;
            mpt: string;
            mpy: string;
            mqy: string;
            mrc: string;
            mrcx: string;
            ms: string;
            mscml: string;
            mseed: string;
            mseq: string;
            msf: string;
            msh: string;
            msi: string;
            msl: string;
            msty: string;
            mts: string;
            mus: string;
            musicxml: string;
            mvb: string;
            mwf: string;
            mxf: string;
            mxl: string;
            mxml: string;
            mxs: string;
            mxu: string;
            'n-gage': string;
            n3: string;
            nb: string;
            nbp: string;
            nc: string;
            ncx: string;
            nfo: string;
            ngdat: string;
            nitf: string;
            nlu: string;
            nml: string;
            nnd: string;
            nns: string;
            nnw: string;
            npx: string;
            nsc: string;
            nsf: string;
            ntf: string;
            nzb: string;
            oa2: string;
            oa3: string;
            oas: string;
            obd: string;
            obj: string;
            oda: string;
            odb: string;
            odc: string;
            odf: string;
            odft: string;
            odg: string;
            odi: string;
            odm: string;
            odp: string;
            ods: string;
            odt: string;
            oga: string;
            ogg: string;
            ogv: string;
            ogx: string;
            omdoc: string;
            onepkg: string;
            onetmp: string;
            onetoc: string;
            onetoc2: string;
            opf: string;
            opml: string;
            oprc: string;
            opus: string;
            org: string;
            osf: string;
            osfpvg: string;
            otc: string;
            otf: string;
            otg: string;
            oth: string;
            oti: string;
            otp: string;
            ots: string;
            ott: string;
            oxps: string;
            oxt: string;
            p: string;
            p10: string;
            p12: string;
            p7b: string;
            p7c: string;
            p7m: string;
            p7r: string;
            p7s: string;
            p8: string;
            pas: string;
            paw: string;
            pbd: string;
            pbm: string;
            pcap: string;
            pcf: string;
            pcl: string;
            pclxl: string;
            pct: string;
            pcurl: string;
            pcx: string;
            pdb: string;
            pdf: string;
            pfa: string;
            pfb: string;
            pfm: string;
            pfr: string;
            pfx: string;
            pgm: string;
            pgn: string;
            pgp: string;
            pic: string;
            pkg: string;
            pki: string;
            pkipath: string;
            plb: string;
            plc: string;
            plf: string;
            pls: string;
            pml: string;
            png: string;
            pnm: string;
            portpkg: string;
            pot: string;
            potm: string;
            potx: string;
            ppam: string;
            ppd: string;
            ppm: string;
            pps: string;
            ppsm: string;
            ppsx: string;
            ppt: string;
            pptm: string;
            pptx: string;
            pqa: string;
            prc: string;
            pre: string;
            prf: string;
            ps: string;
            psb: string;
            psd: string;
            psf: string;
            pskcxml: string;
            ptid: string;
            pub: string;
            pvb: string;
            pwn: string;
            pya: string;
            pyv: string;
            qam: string;
            qbo: string;
            qfx: string;
            qps: string;
            qt: string;
            qwd: string;
            qwt: string;
            qxb: string;
            qxd: string;
            qxl: string;
            qxt: string;
            ra: string;
            ram: string;
            rar: string;
            ras: string;
            rcprofile: string;
            rdf: string;
            rdz: string;
            rep: string;
            res: string;
            rgb: string;
            rif: string;
            rip: string;
            ris: string;
            rl: string;
            rlc: string;
            rld: string;
            rm: string;
            rmi: string;
            rmp: string;
            rms: string;
            rmvb: string;
            rnc: string;
            roa: string;
            roff: string;
            rp9: string;
            rpss: string;
            rpst: string;
            rq: string;
            rs: string;
            rsd: string;
            rss: string;
            rtf: string;
            rtx: string;
            s: string;
            s3m: string;
            saf: string;
            sbml: string;
            sc: string;
            scd: string;
            scm: string;
            scq: string;
            scs: string;
            scurl: string;
            sda: string;
            sdc: string;
            sdd: string;
            sdkd: string;
            sdkm: string;
            sdp: string;
            sdw: string;
            see: string;
            seed: string;
            sema: string;
            semd: string;
            semf: string;
            ser: string;
            setpay: string;
            setreg: string;
            'sfd-hdstx': string;
            sfs: string;
            sfv: string;
            sgi: string;
            sgl: string;
            sgm: string;
            sgml: string;
            sh: string;
            shar: string;
            shf: string;
            sid: string;
            sig: string;
            sil: string;
            silo: string;
            sis: string;
            sisx: string;
            sit: string;
            sitx: string;
            skd: string;
            skm: string;
            skp: string;
            skt: string;
            sldm: string;
            sldx: string;
            slt: string;
            sm: string;
            smf: string;
            smi: string;
            smil: string;
            smv: string;
            smzip: string;
            snd: string;
            snf: string;
            so: string;
            spc: string;
            spf: string;
            spl: string;
            spot: string;
            spp: string;
            spq: string;
            spx: string;
            sql: string;
            src: string;
            srt: string;
            sru: string;
            srx: string;
            ssdl: string;
            sse: string;
            ssf: string;
            ssml: string;
            st: string;
            stc: string;
            std: string;
            stf: string;
            sti: string;
            stk: string;
            stl: string;
            str: string;
            stw: string;
            sub: string;
            sus: string;
            susp: string;
            sv4cpio: string;
            sv4crc: string;
            svc: string;
            svd: string;
            svg: string;
            svgz: string;
            swa: string;
            swf: string;
            swi: string;
            sxc: string;
            sxd: string;
            sxg: string;
            sxi: string;
            sxm: string;
            sxw: string;
            t: string;
            t3: string;
            taglet: string;
            tao: string;
            tar: string;
            tcap: string;
            tcl: string;
            teacher: string;
            tei: string;
            teicorpus: string;
            tex: string;
            texi: string;
            texinfo: string;
            text: string;
            tfi: string;
            tfm: string;
            tga: string;
            thmx: string;
            tif: string;
            tiff: string;
            tmo: string;
            torrent: string;
            tpl: string;
            tpt: string;
            tr: string;
            tra: string;
            trm: string;
            tsd: string;
            tsv: string;
            ttc: string;
            ttf: string;
            ttl: string;
            twd: string;
            twds: string;
            txd: string;
            txf: string;
            txt: string;
            u32: string;
            udeb: string;
            ufd: string;
            ufdl: string;
            ulx: string;
            umj: string;
            unityweb: string;
            uoml: string;
            uri: string;
            uris: string;
            urls: string;
            ustar: string;
            utz: string;
            uu: string;
            uva: string;
            uvd: string;
            uvf: string;
            uvg: string;
            uvh: string;
            uvi: string;
            uvm: string;
            uvp: string;
            uvs: string;
            uvt: string;
            uvu: string;
            uvv: string;
            uvva: string;
            uvvd: string;
            uvvf: string;
            uvvg: string;
            uvvh: string;
            uvvi: string;
            uvvm: string;
            uvvp: string;
            uvvs: string;
            uvvt: string;
            uvvu: string;
            uvvv: string;
            uvvx: string;
            uvvz: string;
            uvx: string;
            uvz: string;
            vcard: string;
            vcd: string;
            vcf: string;
            vcg: string;
            vcs: string;
            vcx: string;
            vis: string;
            viv: string;
            vob: string;
            vor: string;
            vox: string;
            vrml: string;
            vsd: string;
            vsf: string;
            vss: string;
            vst: string;
            vsw: string;
            vtu: string;
            vxml: string;
            w3d: string;
            wad: string;
            wav: string;
            wax: string;
            wbmp: string;
            wbs: string;
            wbxml: string;
            wcm: string;
            wdb: string;
            wdp: string;
            weba: string;
            webm: string;
            webm1: string;
            webp: string;
            wg: string;
            wgt: string;
            wks: string;
            wm: string;
            wma: string;
            wmd: string;
            wmf: string;
            wml: string;
            wmlc: string;
            wmls: string;
            wmlsc: string;
            wmv: string;
            wmx: string;
            wmz: string;
            woff: string;
            woff2: string;
            wpd: string;
            wpl: string;
            wps: string;
            wqd: string;
            wri: string;
            wrl: string;
            wsdl: string;
            wspolicy: string;
            wtb: string;
            wvx: string;
            x32: string;
            x3d: string;
            x3db: string;
            x3dbz: string;
            x3dv: string;
            x3dvz: string;
            x3dz: string;
            xaml: string;
            xap: string;
            xar: string;
            xbap: string;
            xbd: string;
            xbm: string;
            xdf: string;
            xdm: string;
            xdp: string;
            xdssc: string;
            xdw: string;
            xenc: string;
            xer: string;
            xfdf: string;
            xfdl: string;
            xht: string;
            xhtml: string;
            xhvml: string;
            xif: string;
            xla: string;
            xlam: string;
            xlc: string;
            xlf: string;
            xlm: string;
            xls: string;
            xlsb: string;
            xlsm: string;
            xlsx: string;
            xlt: string;
            xltm: string;
            xltx: string;
            xlw: string;
            xm: string;
            xml: string;
            xo: string;
            xop: string;
            xpi: string;
            xpl: string;
            xpm: string;
            xpr: string;
            xps: string;
            xpw: string;
            xpx: string;
            xsl: string;
            xslt: string;
            xsm: string;
            xspf: string;
            xul: string;
            xvm: string;
            xvml: string;
            xwd: string;
            xyz: string;
            xz: string;
            yang: string;
            yin: string;
            z1: string;
            z2: string;
            z3: string;
            z4: string;
            z5: string;
            z6: string;
            z7: string;
            z8: string;
            zaz: string;
            zip: string;
            zir: string;
            zirz: string;
            zmm: string;
        }>;
        config_override: {
            url: object;
            onedrive: object;
            google_drive: object;
            clipboard: object;
            box: object;
            dalle: object;
        };
        style_override: typeof external_sources_ui_styles;
    });
    _custupInnerContainer: HTMLDivElement;
    callbackFn: Function;
    standalone_mode: boolean;
    /**
     * @private @param {HTMLDivElement} container_ui_container
     * @private @param {HTMLDivElement} custup_close_btn
     * @private @param {Function | undefined} custup_show_message
     * @private @param {Function | undefined} handle_custom_scroll
     * @private @param {Array<keyof file_types>} allowed_mime_types
     * @private @param {Function | undefined} onclose
     */
    private container_ui_container;
    custup_close_btn: HTMLDivElement | undefined;
    custup_show_message_fn: Function | undefined;
    handle_custom_scroll: {
        customScroll: () => null;
        customScrollbar: () => null;
        handleSetPointerEV: () => null;
    };
    allowed_mime_types: any[];
    onclose: Function | undefined;
    setElementMediaQuery: any;
    /**
     * @private @param {string} source_type
     */
    private source_type;
    /**
     * @private @param {string} external_source_style
     */
    private external_source_style;
    /**
     * URL Source
     */
    URL_source_container: any;
    URL_source_inner_container_1: any;
    URL_source_inner_container_2: any;
    URL_source_input_container: any;
    URL_source_button_container: any;
    URL_source_text_input: any;
    URL_source_button: any;
    /**
     * Google Drive Picker
     */
    googleDrivePickerTokenClient: any;
    accessToken: null;
    googleDrivePickerInited: boolean;
    gisInited: boolean;
    dropboxUIContainer: any;
    /**
     * OneDrive source
     */
    onedriveAuthConfig: {
        msalParams: {
            auth: {
                authority: string;
                clientId: string;
                redirectUri: string;
            };
        };
        params: {
            sdk: string;
            entry: {
                oneDrive: {
                    files: {};
                };
            };
            authentication: {};
            messaging: {
                origin: string;
                channelId: string;
            };
            typesAndSources: {
                mode: string;
                pivots: {
                    oneDrive: boolean;
                    recent: boolean;
                };
            };
        };
    };
    onedriveSetupConfig: {
        msalLink: string;
        baseUrl: string;
    };
    msalApp: any;
    onedrivePickerWin: any;
    onedrivePickerPort: any;
    /**
     * @private @param {HTMLDivElement} dalleOuterContainer
     */
    private dalleOuterContainer;
    /**
     * @public @param {HTMLDivElement} dalleInitialPageContainer
     */
    public dalleInitialPageContainer: any;
    /**
     * @public @param {HTMLDivElement} dallePreviewPageContainer
     */
    public dallePreviewPageContainer: any;
    dalleResponseData: any[];
    dalle_file_data: any[];
    dalle_selected_files: any[];
    config_override: {
        url: {};
        onedrive: {};
        google_drive: {
            authConfig: {
                client_id: string;
                api_key: string;
                app_id: string;
                scopes: string;
            };
        };
        clipboard: {};
        box: {
            authConfig: {
                developerToken: string;
                cssLink: string;
                jsLink: string;
                folder_id: string;
            };
            pickerConfig: {
                chooseButtonLabel: undefined;
                sortBy: string;
                sortDirection: string;
                logoUrl: string;
                extensions: never[];
                maxSelectable: number;
                canUpload: boolean;
                canSetShareAccess: boolean;
                canCreateNewFolder: boolean;
                sharedLink: string;
                sharedLinkPassword: string;
                modal: string;
                size: undefined;
                isTouch: boolean;
                autoFocus: boolean;
                defaultView: string;
                cancelButtonLabel: undefined;
                requestInterceptor: undefined;
                responseInterceptor: undefined;
            };
        };
        dalle: {
            endpoint: string;
            api_key: string;
            model: string;
            quality: string;
            size: string;
            n: number;
            response_format: {
                b64: string;
            };
        };
        dropbox: {
            authConfig: {};
            options: {
                cancel: () => void;
                linkType: string;
                multiselect: boolean;
                extensions: never[];
                folderselect: boolean;
            };
        };
        style_override: {};
    };
    /**
     * @deprecated because this method is very buggy and I found a new way to implement it
     * @private @method updateObjectData - sets second level object key's value
     * @param {object} targetObject - the object to update
     * @param {string} key - the first-level key to update
     * @param {any} dataObj - the data to set
     * @returns object
     */
    private updateObjectData;
    /**
      *
      * @private set_class_name
      *
      * @param style_key_name string the name of the style
      * @param element_to_style HTMLElement
      * @returns {void}
      *
      */
    private set_class_name;
    /**
     * @private getRandChars
     * @param {string} identifyer
     * @returns {string}
     */
    private getRandChars;
    initialize(): void;
    loadGoogleDrivePickerScripts(): void;
    loadDropboxPickerScript(): void;
    loadBoxPickerScript(): void;
    loadOneDrivePickerScript(): void;
    setupCustupCloseBtn(): void;
    createContainerUI(): void;
    destroyContainerUI(silent?: boolean): void;
    makeURLSourceUi(): void;
    handleAddFileFromURLSource(): Promise<void>;
    dropboxIsInitialized(): boolean;
    handleAddFileFromDropbox(): void;
    addDropboxToUI(): void;
    /**
     * @private @method dropboxOnFileChosen
     * @param {Array<any>} files - files array returned from dropbox
     */
    private dropboxOnFileChosen;
    handleAddFileFromGoogleDrive(): void;
    isGooglePickerScriptLoaded(): boolean;
    /**
     * Callback after the API client is loaded. Loads the
     * discovery doc to initialize the API.
     */
    initializeGoogleDrivePicker(): Promise<void>;
    loadGAPI(): void;
    googleAPIisLoaded(): void;
    createGoogleDrivePicker(): void;
    googleDrivePickerCallback(data: any): Promise<void>;
    isBoxScriptLoaded(): boolean;
    handleAddFileFromBox(): void;
    addBoxPickerToUI(): void;
    handleAddFileFromOneDrive(): void;
    addOneDrivePickerToUI(): void;
    getOneDriveToken(command: any): Promise<string>;
    /**
         * Combines an arbitrary set of paths ensuring and normalizes the slashes
         *
         * @param paths 0 to n path parts to combineOneDriveURL
         */
    combineOneDriveURL(...paths: any[]): string;
    launchPicker(): Promise<void>;
    messageListener(message: any): Promise<void>;
    handleAddFileFromOpenaiDALLE(): void;
    createDalleInitialUI(): void;
    removeDalleInitialUI(): void;
    resetDalleData(): void;
    base64ToBlob(base64: any, type?: string): Blob;
    generateImageWithOpenAIDALLE(ev: any, inputEl: any): Promise<void>;
    previewGeneratedDalleImages(): any;
    updateDalleSelectedFilesCounter(counterElm: any): void;
    acceptDalleGeneratedFiles(): void;
}
import { external_sources_ui_styles } from "../utils/_styles.js";
//# sourceMappingURL=externalsources.d.ts.map